SELECT p.protocol,
       p.title,
       p.investigatorId,
       p.external_id,
       protocol.usda_level,
       protocol.PPQ_Numbers,
       protocol.PROTOCOL_State,
       p.approve,
       protocol.Approval_Date,
       protocol.Annual_Update_Due,
       protocol.Three_year_Expiration,
       p.lastAnnualReview,
       p.enddate,
       protocol.description,
FROM protocol p