/*' updated 2022-07-25 2nd tgry*/
SELECT protocol.protocol,
protocol.title,
protocol.investigatorId,
protocol.approve,
protocol.lastAnnualReview,
protocol.enddate,
protocol.external_id,
protocol.ibc_approval_num,
protocol.usda_level,
protocol.last_modification,
protocol.description,
protocol.container,
protocol.contacts as Template_OID,
protocol.project_type as Protocol_State,
protocol.Approval_Date,
protocol.Annual_Update_Due,
protocol.Three_year_Expiration,
protocol.last_modified,
protocol.displayName,
protocol.annualReviewDate,
protocol.daysUntilAnnualReview,
protocol.renewalDate,
protocol.daysUntilRenewal
FROM protocol