#!/bin/bash
#assume that some process initialized from mysql has dumped text files. Those files should be
#generated by a command like this:
#
# mysqldump -u username --password=xxxx --tab=$MYSQL_DUMPDIR --no-create-info colony --ignore-table=tmp_table
#
# Note that MYSQL_DUMPDIR in that case must be relative to the mysql SERVER, as the server
# itself is dumping the files
#
# DUMPDIR as a directory relative to THIS script. Change following line:
#
DUMPDIR=/Users/bimber/mysql-dump
FIXEDDIR=/Users/bimber/mysql-dump

POSTGRES_DB=labkey

#
# Iterate over the dumped dataset files.
for dumpfile in $DUMPDIR/datasets/*.tsv
do
  fname=${dumpfile##*/}
  basename=${fname%%.*} 

#TODO: update for SQLServer
      echo "psql TRUNCATE col_dump.$basename"
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "TRUNCATE col_dump.$basename;" 
      if [ $? -ne 0 ]; then
         echo "Error truncating col_dump.$basename; Perhaps security error?"  >&2
         exit 1
      fi

      echo "copy col_dump.$basename FROM ${FIXEDDIR}/datasets/$fname" 
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "\copy col_dump.$basename FROM '${FIXEDDIR}/datasets/$fname' delimiter as '\t' csv header"  
      if [ $? -ne 0 ]; then
         echo "Error copying data see errors.log for details" >&2
#         exit 1
      fi
  echo
done

# Iterate over the dumped lists.
for dumpfile in $DUMPDIR/lists/*.tsv
do
  fname=${dumpfile##*/}
  basename=${fname%%.*}

      echo "psql TRUNCATE col_dump.$basename" 
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "TRUNCATE col_dump.$basename;" 
      if [ $? -ne 0 ]; then
         echo "Error truncating col_dump.$basename; Perhaps security error?"  >&2
         exit 1
      fi

      echo "copy col_dump.$basename FROM ${FIXEDDIR}/lists/$fname" 
      /usr/local/pgsql/bin/psql -U labkey -d ${POSTGRES_DB} -c "\copy col_dump.$basename FROM '${FIXEDDIR}/lists/$fname' delimiter as '\t' csv header"  
      if [ $? -ne 0 ]; then
         echo "Error copying data see errors.log for details" >&2
         exit 1
      fi
  echo
done

echo "Load successful!"
exit 0
