SELECT p.rowid,
       p.Protocol_ID,
       BAseProtocol,
       RevisionNumber,
       p.Template_OID,
       p.Protocol_OID,
       p.Protocol_Title,
       p.PI_ID,
       p.PI_First_Name,
       p.PI_Last_Name,
       p.PI_Email,
       p.PI_Phone,
       p.USDA_Level,
       p.Approval_Date,
       p.Annual_Update_Due,
       p.Three_year_Expiration,
       p.Last_Modified,
       p.createdby,
       p.created,
       p.modifiedby,
       p.modified,
       p.PROTOCOL_State,
       p.PPQ_Numbers,
       p.Description
FROM eIACUCPopulateeIACUCData.sql p