SELECT DISTINCT p1.rowid,
       p1.Protocol_ID,
       p1.BaseProtocol,
       p1.RevisionNumber,
       p1.Template_OID,
       p1.Protocol_OID,
       p1.Protocol_Title,
       p1.PI_ID,
       p1.PI_First_Name,
       p1.PI_Last_Name,
       p1.PI_Email,
       p1.PI_Phone,
       p1.USDA_Level,
       p1.Approval_Date,
       p1.Annual_Update_Due,
       p1.Three_year_Expiration,
       p1.Last_Modified,
       p1.createdby,
       p1.created,
       p1.modifiedby,
       p1.modified,
       p1.Protocol_State,
       p1.PPQ_Numbers,
       p1.Description,
       p2.Protocol
FROM onprc_ehr.eIACUC2Data AS p1
LEFT JOIN ehr.project AS p2 ON p1.BaseProtocol = p2.protocol.external_id