SELECT protocol.protocol,
protocol.title,
protocol.investigatorId,
protocol.approve,
protocol.lastAnnualReview,
protocol.enddate,
protocol.external_id,
protocol.ibc_approval_num,
protocol.usda_level,
protocol.last_modification,
protocol.description,
protocol.container,
protocol.contacts,
protocol.PPQ_Numbers,
protocol.PROTOCOL_State,
protocol.Template_OID,
protocol.Approval_Date,
protocol.Annual_Update_Due,
protocol.Three_year_Expiration,
protocol.last_modified,
protocol.displayName,
protocol.annualReviewDate,
protocol.daysUntilAnnualReview,
protocol.renewalDate,
protocol.daysUntilRenewal
FROM ehr.protocol