SELECT d.Id,
       d.date,
       d.reviewdate,
       d.category,
       d.remark,
       d.taskid,
       d.requestid,
       d.description,
       d.performedby,
       d.enddate,
       d.assignedvet,
       d.Container,
       d.history,
       d.isAssignedAtTime,
       d.isAssignedToProtocolAtTime,
       d.latestHx,
       d.mostRecentP2,
       d.mostRecentRemark,
       d.mostRecentCeg_Plan,
       d.todaysP2,
       d.yesterdaysP2,
       d.todaysRemarks,
       d.assessmentOnOpenDate,
       d.proceduresPerformed,
       d.surgeryfollowupDays,
       d.caseHistory,
       d.problemCategories,
       d.allProblemCategories,
       d.isActive,
       d.isOpen,
       d.lastVetReview,
       d.daysSinceLastVetReview,
       d.lastRoundsObs,
       d.daysSinceLastRounds,
       d.enteredSinceVetReview,
       d.QCState
 FROM  StudyDetails_RandalData s, Site.{substitutePath moduleProperty('EHR','EHRStudyContainer')}.study.cases d
    where (active = 'y' and s.rh = d.id)