SELECT d.Id,
       d.date,
       d.testid,
       d.result,
       d.resultOORIndicator,
       d.units,
       d.qualresult,
       d.method,
       d.runid,
       d.resultNumber,
       d.resultInRange,
       d.remark,
       d.description,
       d.taskid,
       d.performedby,
       d.requestid,
       d.Container,
       d.history,
       d.isAssignedAtTime,
       d.isAssignedToProtocolAtTime,
       d.enteredSinceVetReview,
       d.QCState
 FROM  StudyDetails_RandalData s, Site.{substitutePath moduleProperty('EHR','EHRStudyContainer')}.study.hematologyResults d
    where (active = 'y' and s.rh = d.id)