SELECT d.Id,
       d.date,
       d.source,
       d.acquisitionType,
       d.rearingType,
       d.gender,
       d.species,
       d.geographic_origin,
       d.dam,
       d.sire,
       d.birth,
       d.estimated,
       d.originalId,
       d.arrivalId,
       d.cites,
       d.customsDate,
       d.remark,
       d.description,
       d.taskid,
       d.project,
       d.performedby,
       d.requestid,
       d.Container,
       d.isNumericId,
       d.history,
       d.isAssignedAtTime,
       d.isAssignedToProtocolAtTime,
       d.enteredSinceVetReview,
       d.QCState
 FROM  StudyDetails_RandalData s, "/ONPRC/EHR".study.arrival d
    where (active = 'y' and s.rh = d.id)