SELECT d.Id,
       d.date,
       d.enddate,
       d.project,
       d.chargetype,
       d.code,
       d.Billable,
       d.qualifier,
       d.reason,
       d.route,
       d.concentration,
       d.conc_units,
       d.dosage,
       d.dosage_units,
       d.volume,
       d.vol_units,
       d.amount,
       d.amount_units,
       d.outcome,
       d.lot,
       d.remark,
       d.category,
       d.begindate,
       d.description,
       d.taskid,
       d.performedby,
       d.requestid,
       d.Container,
       d.history,
       d.isAssignedAtTime,
       d.isAssignedToProtocolAtTime,
       d.enteredSinceVetReview,
       d.QCState
 FROM  StudyDetails_RandalData s, Site.{substitutePath moduleProperty('EHR','EHRStudyContainer')}.study.drug d
    where (active = 'y' and s.rh = d.id)