SELECT d.Id,
       d.date,
       d.date_type,
       d.birth_condition,
       d.room,
       d.cage,
       d.dam,
       d.gender,
       d.teeth,
       d.weight,
       d.wdate,
       d.type,
       d.species,
       d.geographic_origin,
       d.sire,
       d.conception,
       d.conceptualDay,
       d.remark,
       d.description,
       d.taskid,
       d.project,
       d.performedby,
       d.requestid,
       d.Container,
       d.isNumericId,
       d.history,
       d.isAssignedAtTime,
       d.isAssignedToProtocolAtTime,
       d.enteredSinceVetReview,
       d.QCState
 FROM  StudyDetails_RandalData s, Site.{substitutePath moduleProperty('EHR','EHRStudyContainer')}.study.birth d
    where (active = 'y' and s.rh = d.id)