SELECT d.Id,
        d.project,
        d.date,
        d.projectedRelease,
        d.enddate,
        d.dType,
        d.assignCondition,
        d.projectedReleaseCondition,
        d.releaseCondition,
        d.releaseType,
        d.remark,
        d.description,
        d.taskid,
        d.requestid,
        d.Container,
        d.isActive,
        d.history,
        d.enteredSinceVetReview,
        d.QCState
 FROM  StudyDetails_RandalData s, Site.{substitutePath moduleProperty('EHR','EHRStudyContainer')}".study.assignment d
    where (active = 'y' and s.rh = d.id)