CREATE SCHEMA IF NOT EXISTS onprc_ehr_compliancedb;

CREATE TABLE onprc_ehr_compliancedb.SciShield_Data
(
    RowId SERIAL NOT NULL,
    employeeId VARCHAR(255) NOT NULL,
    requirementname VARCHAR(255) NULL,
    Date TIMESTAMP NULL,
    Container ENTITYID NOT NULL,
    comment VARCHAR(2000) NULL,
    CreatedBy USERID,
    Created TIMESTAMP,
    ModifiedBy USERID,
    Modified TIMESTAMP,
    processed INT NULL,

    CONSTRAINT PK_ScieShield_Data PRIMARY KEY (RowId),
    CONSTRAINT FK_ONPRC_EHR_COMPLIANCE_SCISHIELD_DATA_CONTAINER FOREIGN KEY (Container) REFERENCES core.Containers (EntityId)
);
CREATE INDEX IX_ONPRC_EHR_COMPLIANCEDB_SCISHIELD_DATA_CONTAINER ON onprc_ehr_compliancedb.SciShield_Data (Container);

CREATE TABLE onprc_ehr_compliancedb.SciShield_Reference_Data
(
    rowId SERIAL NOT NULL,
    label VARCHAR(250) NULL,
    value VARCHAR(255) NOT NULL,
    columnName VARCHAR(255) NOT NULL,
    sort_order INTEGER NULL,
    endDate TIMESTAMP NULL,
    Container ENTITYID NOT NULL,
    CreatedBy USERID,
    Created TIMESTAMP,
    ModifiedBy USERID,
    Modified TIMESTAMP,

    CONSTRAINT pk_SciShield_reference PRIMARY KEY (value),
    CONSTRAINT FK_ONPRC_EHR_COMPLIANCE_REFERENCE_DATA_CONTAINER FOREIGN KEY (Container) REFERENCES core.Containers (EntityId)
);
CREATE INDEX IX_ONPRC_EHR_COMPLIANCEDB_SCISHIELD_REFERENCE_DATA_CONTAINER ON onprc_ehr_compliancedb.SciShield_Reference_Data (Container);

CREATE TABLE onprc_ehr_compliancedb.SciShieldTemp (
    searchID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    employeeid VARCHAR(500) NULL,
    requirementname VARCHAR(3000) NULL,
    completeddate TIMESTAMP NULL,
    comment VARCHAR(300) NULL,
    createddate TIMESTAMP NULL,
    rowid INT NULL
);

CREATE TABLE onprc_ehr_compliancedb.SciShieldMasterTemp (
    searchID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    employeeid VARCHAR(500) NULL,
    requirementname VARCHAR(3000) NULL,
    completeddate TIMESTAMP NULL,
    comment VARCHAR(300) NULL,
    createddate TIMESTAMP NULL,
    rowid INT NULL
);

CREATE TABLE onprc_ehr_compliancedb.ComplianceProcedureReport (
    rowid SERIAL NOT NULL,
    employeeid VARCHAR(300) NULL,
    requirementname VARCHAR(4000) NULL,
    unit VARCHAR(500) NULL,
    category VARCHAR(500) NULL,
    trackingflag VARCHAR(100) NULL,
    email VARCHAR(500) NULL,
    lastname VARCHAR(500) NULL,
    firstname VARCHAR(500) NULL,
    host VARCHAR(500) NULL,
    supervisor VARCHAR(500) NULL,
    trainee_type VARCHAR(500) NULL,
    times_completed SMALLINT NULL,
    expired_period SMALLINT NULL,
    new_expired_period SMALLINT NULL,
    mostrecentcompleted_date TIMESTAMP NULL,
    comment VARCHAR(4000) NULL,
    snooze_date TIMESTAMP NULL,
    months_until_renewal DOUBLE PRECISION NULL,
    requirement_name_type VARCHAR(1000) NULL
);

CREATE TABLE onprc_ehr_compliancedb.ComplianceRecentReport (
    rowid SERIAL NOT NULL,
    employeeid VARCHAR(300) NULL,
    requirementname VARCHAR(4000) NULL,
    unit VARCHAR(500) NULL,
    category VARCHAR(500) NULL,
    trackingflag VARCHAR(100) NULL,
    email VARCHAR(500) NULL,
    lastname VARCHAR(500) NULL,
    firstname VARCHAR(500) NULL,
    host VARCHAR(500) NULL,
    supervisor VARCHAR(500) NULL,
    trainee_type VARCHAR(500) NULL,
    times_completed SMALLINT NULL,
    expired_period SMALLINT NULL,
    new_expired_period SMALLINT NULL,
    mostrecentcompleted_date TIMESTAMP NULL,
    comment VARCHAR(4000) NULL,
    snooze_date TIMESTAMP NULL,
    months_until_renewal DOUBLE PRECISION NULL,
    requirement_name_type VARCHAR(1000) NULL
);

CREATE TABLE onprc_ehr_compliancedb.RequirementsPerEmployee (
    RowId SERIAL NOT NULL,
    EmployeeId VARCHAR(255) NOT NULL,
    RequirementName VARCHAR(255) NOT NULL,
    CreatedBy USERID,
    Created TIMESTAMP,
    ModifiedBy USERID,
    Modified TIMESTAMP,
    trackingflag VARCHAR(100),

    CONSTRAINT PK_RequirementsPerEmployeename PRIMARY KEY (RowId)
);

CREATE INDEX IF NOT EXISTS IX_completiondates_trainer ON ehr_compliancedb.completiondates(trainer);

CREATE OR REPLACE FUNCTION onprc_ehr_compliancedb.p_SciShieldToPrimeProcess()
RETURNS integer AS $$
DECLARE
    _requirementnameFinal VARCHAR(2000);
    _requirementname      VARCHAR(2000);
    _employeeid           VARCHAR(500);
    _Completiondate       TIMESTAMP;
    _SciShieldID          INT;
    rec                   RECORD;
BEGIN
    ---- Reset temp table
    DELETE FROM onprc_ehr_compliancedb.SciShieldTemp;

    IF EXISTS (SELECT 1 FROM onprc_ehr_compliancedb.SciShield_Data WHERE processed IS NULL) THEN
        INSERT INTO onprc_ehr_compliancedb.SciShieldTemp
            (employeeid, requirementname, completeddate, createddate, rowid)
        SELECT
            employeeid,
            requirementname,
            date,
            now(),
            rowid
        FROM onprc_ehr_compliancedb.SciShield_Data
        WHERE processed IS NULL
        ORDER BY employeeid, requirementname, date DESC;
    ELSE
        RETURN 0;
    END IF;

    FOR rec IN
        SELECT searchID, employeeid, requirementname, completeddate, rowid
        FROM onprc_ehr_compliancedb.SciShieldTemp
        ORDER BY searchID
    LOOP
        _requirementnameFinal := '';
        _requirementname := COALESCE(rec.requirementname, '');
        _employeeid := TRIM(LOWER(COALESCE(rec.employeeid, '')));
        _Completiondate := rec.completeddate;
        _SciShieldID := rec.rowid;

        -- Validate requirementname
        IF EXISTS (SELECT 1 FROM onprc_ehr_compliancedb.SciShield_Reference_Data WHERE label = _requirementname AND columnname = 'requirementname') THEN
            SELECT value INTO _requirementnameFinal
            FROM onprc_ehr_compliancedb.SciShield_Reference_Data
            WHERE label = _requirementname AND columnname = 'requirementname'
            LIMIT 1;
        ELSIF EXISTS (SELECT 1 FROM ehr_compliancedb.requirements WHERE requirementname = _requirementname) THEN
            SELECT requirementname INTO _requirementnameFinal
            FROM ehr_compliancedb.requirements
            WHERE requirementname = _requirementname
            LIMIT 1;
        ELSE
            UPDATE onprc_ehr_compliancedb.SciShield_Data ss
            SET processed = 3
            WHERE ss.rowid = _SciShieldID;

            CONTINUE;
        END IF;

        -- Validate if the record already exists
        IF EXISTS (SELECT 1 FROM ehr_compliancedb.completiondates WHERE employeeid = _employeeid AND requirementname = _requirementnameFinal AND date = _Completiondate) THEN
            UPDATE onprc_ehr_compliancedb.SciShield_Data ss
            SET processed = 4
            WHERE ss.rowid = _SciShieldID;

            CONTINUE;
        END IF;

        -- Validate if the employeeid is defined
        IF NOT EXISTS (SELECT 1 FROM ehr_compliancedb.employees WHERE employeeid = _employeeid AND enddate IS NULL) THEN
            UPDATE onprc_ehr_compliancedb.SciShield_Data ss
            SET processed = 2
            WHERE ss.rowid = _SciShieldID;

            CONTINUE;
        END IF;

        -- If all previous version were validated proceed with the record insert
        IF NOT EXISTS (SELECT 1 FROM ehr_compliancedb.completiondates WHERE employeeid = _employeeid AND requirementname = _requirementnameFinal AND date = _Completiondate) THEN
            INSERT INTO ehr_compliancedb.completiondates
                (employeeid, requirementname, date, trainer, container, created, createdby, modified, modifiedby)
            VALUES
                (_employeeid, _requirementnameFinal, _Completiondate, 'ONLINE TRAINING', 'CD170458-C55F-102F-9907-5107380A54BE', now(), 2595, now(), 2595);

            UPDATE onprc_ehr_compliancedb.SciShield_Data ss
            SET processed = 1
            WHERE ss.rowid = _SciShieldID;
        END IF;
    END LOOP;

    -- Create master records of the last most recent entries
    IF EXISTS (SELECT 1 FROM onprc_ehr_compliancedb.SciShieldTemp) THEN
        INSERT INTO onprc_ehr_compliancedb.SciShieldMasterTemp
            (employeeid, requirementname, completeddate, comment, createddate, rowid)
        SELECT
            employeeid,
            requirementname,
            completeddate,
            comment,
            createddate,
            rowid
        FROM onprc_ehr_compliancedb.SciShieldTemp;
    END IF;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 1;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION onprc_ehr_compliancedb.p_ComplianceTranslatestringUpdate()
RETURNS integer AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM ehr_compliancedb.EmployeePerUnit WHERE unit LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.EmployeePerUnit SET unit = replace(unit, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.EmployeePerUnit WHERE category LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.EmployeePerUnit SET category = replace(category, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.Employees WHERE majorudds LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.Employees SET majorudds = replace(majorudds, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.Employees WHERE unit LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.Employees SET unit = replace(unit, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.Employees WHERE category LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.Employees SET category = replace(category, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.requirements WHERE requirementname LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.requirements SET requirementname = replace(requirementname, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.EmployeeRequirementExemptions WHERE requirementname LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.EmployeeRequirementExemptions SET requirementname = replace(requirementname, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.unit_names WHERE unit LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.unit_names SET unit = replace(unit, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.RequirementsPerCategory WHERE RequirementName LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.RequirementsPerCategory SET requirementname = replace(requirementname, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.RequirementsPerCategory WHERE category LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.RequirementsPerCategory SET category = replace(category, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.RequirementsPerCategory WHERE unit LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.RequirementsPerCategory SET unit = replace(unit, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.completiondates WHERE requirementname LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.completiondates SET requirementname = replace(requirementname, 'arrs', 'DCM');
    END IF;

    IF EXISTS (SELECT 1 FROM ehr_compliancedb.EmployeeCategory WHERE categoryname LIKE '%arrs%') THEN
        UPDATE ehr_compliancedb.EmployeeCategory SET categoryname = replace(categoryname, 'arrs', 'DCM');
    END IF;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 1;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION onprc_ehr_compliancedb.p_ComplianceRecentOverDueSoon_Process()
RETURNS integer AS $$
BEGIN
    DELETE FROM onprc_ehr_compliancedb.ComplianceRecentReport;

    INSERT INTO onprc_ehr_compliancedb.ComplianceRecentReport
    (
        requirementname,
        employeeid,
        unit,
        category,
        trackingflag,
        email,
        lastname,
        firstname,
        host,
        supervisor,
        trainee_type,
        requirement_name_type,
        times_completed,
        expired_period,
        new_expired_Period,
        mostrecentcompleted_date,
        comment,
        snooze_date,
        months_until_renewal
    )
    SELECT
        b.requirementname,
        a.employeeid,
        string_agg(a.unit, chr(10)) AS unit,
        string_agg(a.category, chr(10)) AS category,
        string_agg(b.trackingflag, chr(10)) AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = b.requirementname) AS requirement_type,
        (SELECT count(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid) AS times_Completed,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = b.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid) AS mostrecentcompleted_date,
        (
            SELECT string_agg(DISTINCT yy.comment, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = b.requirementname AND yy.employeeid = a.employeeid
        ) AS comment,
        (
            SELECT string_agg(DISTINCT yy.snooze_date::text, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = b.requirementname AND yy.employeeid = a.employeeid
        ) AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = b.requirementname AND st.employeeid = a.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = b.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DOUBLE PRECISION
        ) AS MonthsUntilRenewal
    FROM ehr_compliancedb.employeeperunit a, ehr_compliancedb.requirementspercategory b
    WHERE (a.unit = b.unit OR a.category = b.category)
      AND b.requirementname NOT IN (SELECT DISTINCT t.requirementname FROM ehr_compliancedb.employeerequirementexemptions t WHERE a.employeeid = t.employeeid AND b.requirementname = t.requirementname)
      AND a.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE a.employeeid = p.employeeid AND p.enddate IS NULL)
      AND b.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = b.requirementname AND q.dateDisabled IS NULL)
    GROUP BY b.requirementname, a.employeeid

    UNION

    SELECT
        a.requirementname,
        a.employeeid,
        NULL AS unit,
        NULL AS category,
        'None' AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = a.requirementname) AS requirement_type,
        (SELECT count(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS timesCompleted,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = a.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS MostRecentDate,
        (
            SELECT string_agg(DISTINCT yy.comment, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS comment,
        (
            SELECT string_agg(DISTINCT yy.snooze_date::text, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = a.requirementname AND st.employeeid = a.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = a.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DOUBLE PRECISION
        ) AS MonthsUntilRenewal
    FROM ehr_compliancedb.completiondates a
    WHERE a.requirementname NOT IN (
        SELECT DISTINCT h.requirementname
        FROM ehr_compliancedb.employeeperunit k, ehr_compliancedb.requirementspercategory h
        WHERE (k.unit = h.unit OR k.category = h.category) AND a.employeeid = k.employeeid
    )
      AND a.requirementname NOT IN (SELECT DISTINCT t.requirementname FROM ehr_compliancedb.employeerequirementexemptions t WHERE a.employeeid = t.employeeid AND a.requirementname = t.requirementname)
      AND a.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE a.employeeid = p.employeeid AND p.enddate IS NULL)
      AND a.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = a.requirementname AND q.dateDisabled IS NULL)
    GROUP BY a.requirementname, a.employeeid

    UNION

    SELECT
        a.requirementname,
        a.employeeid,
        NULL AS unit,
        NULL AS category,
        'No' AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = a.requirementname) AS requirement_type,
        (SELECT count(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS timesCompleted,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = a.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS MostRecentDate,
        (
            SELECT string_agg(DISTINCT yy.comment, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS comment,
        (
            SELECT string_agg(DISTINCT yy.snooze_date::text, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = a.requirementname AND st.employeeid = a.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = a.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DECIMAL
        ) AS MonthsUntilRenewal
    FROM ehr_compliancedb.employeerequirementexemptions a
    WHERE a.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE a.employeeid = p.employeeid AND p.enddate IS NULL)
      AND a.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = a.requirementname AND q.dateDisabled IS NULL)
    GROUP BY a.requirementname, a.employeeid

    UNION

    SELECT
        j.requirementname,
        j.employeeid,
        NULL AS unit,
        NULL AS category,
        string_agg(j.trackingflag, chr(10)) AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = j.requirementname) AS requirement_type,
        0 AS timesCompleted,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = j.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        NULL AS MostRecentDate,
        '' AS comment,
        NULL AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = j.requirementname AND st.employeeid = j.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = j.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DOUBLE PRECISION
        ) AS MonthsUntilRenewal
    FROM onprc_ehr_compliancedb.RequirementsPerEmployee j
    WHERE j.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE j.employeeid = p.employeeid AND p.enddate IS NULL)
      AND j.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = j.requirementname AND q.dateDisabled IS NULL)
      AND j.requirementname NOT IN (
          SELECT DISTINCT h.requirementname
          FROM ehr_compliancedb.employeeperunit k, ehr_compliancedb.requirementspercategory h
          WHERE (k.unit = h.unit OR k.category = h.category) AND j.employeeid = k.employeeid
      )
      AND j.requirementname NOT IN (SELECT DISTINCT t.requirementname FROM ehr_compliancedb.employeerequirementexemptions t WHERE j.employeeid = t.employeeid AND j.requirementname = t.requirementname)
      AND j.requirementname NOT IN (SELECT DISTINCT k.requirementname FROM ehr_compliancedb.completiondates k WHERE k.employeeid = j.employeeid)
    GROUP BY j.requirementname, j.employeeid
    ORDER BY employeeid, requirementname, mostrecentcompleted_date DESC;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 1;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION onprc_ehr_compliancedb.p_ComplianceProcedureOverDueSoon_Process()
RETURNS integer AS $$
BEGIN
    DELETE FROM onprc_ehr_compliancedb.ComplianceProcedureReport;

    INSERT INTO onprc_ehr_compliancedb.ComplianceProcedureReport
    (
        requirementname,
        employeeid,
        unit,
        category,
        trackingflag,
        email,
        lastname,
        firstname,
        host,
        supervisor,
        trainee_type,
        requirement_name_type,
        times_completed,
        expired_period,
        new_expired_Period,
        mostrecentcompleted_date,
        comment,
        snooze_date,
        months_until_renewal
    )
    SELECT
        b.requirementname,
        a.employeeid,
        string_agg(a.unit, chr(10)) AS unit,
        string_agg(a.category, chr(10)) AS category,
        string_agg(b.trackingflag, chr(10)) AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = b.requirementname) AS requirement_type,
        (SELECT count(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid) AS times_Completed,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = b.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid) AS mostrecentcompleted_date,
        (
            SELECT string_agg(DISTINCT yy.comment, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = b.requirementname AND yy.employeeid = a.employeeid
        ) AS comment,
        (
            SELECT string_agg(DISTINCT yy.snooze_date::text, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = b.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = b.requirementname AND yy.employeeid = a.employeeid
        ) AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = b.requirementname AND st.employeeid = a.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = b.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = b.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DOUBLE PRECISION
        ) AS MonthsUntilRenewal
    FROM ehr_compliancedb.employeeperunit a, ehr_compliancedb.requirementspercategory b
    WHERE (a.unit = b.unit OR a.category = b.category)
      AND b.requirementname NOT IN (SELECT DISTINCT t.requirementname FROM ehr_compliancedb.employeerequirementexemptions t WHERE a.employeeid = t.employeeid AND b.requirementname = t.requirementname)
      AND a.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE a.employeeid = p.employeeid AND p.enddate IS NULL)
      AND b.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = b.requirementname AND q.dateDisabled IS NULL)
    GROUP BY b.requirementname, a.employeeid

    UNION

    SELECT
        a.requirementname,
        a.employeeid,
        NULL AS unit,
        NULL AS category,
        'None' AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = a.requirementname) AS requirement_type,
        (SELECT count(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS timesCompleted,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = a.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS MostRecentDate,
        (
            SELECT string_agg(DISTINCT yy.comment, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS comment,
        (
            SELECT string_agg(DISTINCT yy.snooze_date::text, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = a.requirementname AND st.employeeid = a.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = a.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DOUBLE PRECISION
        ) AS MonthsUntilRenewal
    FROM ehr_compliancedb.completiondates a
    WHERE a.requirementname NOT IN (
        SELECT DISTINCT h.requirementname
        FROM ehr_compliancedb.employeeperunit k, ehr_compliancedb.requirementspercategory h
        WHERE (k.unit = h.unit OR k.category = h.category) AND a.employeeid = k.employeeid
    )
      AND a.requirementname NOT IN (SELECT DISTINCT t.requirementname FROM ehr_compliancedb.employeerequirementexemptions t WHERE a.employeeid = t.employeeid AND a.requirementname = t.requirementname)
      AND a.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE a.employeeid = p.employeeid AND p.enddate IS NULL)
      AND a.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = a.requirementname AND q.dateDisabled IS NULL)
    GROUP BY a.requirementname, a.employeeid

    UNION

    SELECT
        a.requirementname,
        a.employeeid,
        NULL AS unit,
        NULL AS category,
        'No' AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = a.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = a.requirementname) AS requirement_type,
        (SELECT count(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS timesCompleted,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = a.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid) AS MostRecentDate,
        (
            SELECT string_agg(DISTINCT yy.comment, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS comment,
        (
            SELECT string_agg(DISTINCT yy.snooze_date::text, chr(10))
            FROM ehr_compliancedb.completiondates yy
            WHERE yy.date IN (SELECT max(zz.date) FROM ehr_compliancedb.completiondates zz WHERE zz.requirementname = a.requirementname AND zz.employeeid = a.employeeid)
              AND yy.requirementname = a.requirementname AND yy.employeeid = a.employeeid
        ) AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = a.requirementname AND st.employeeid = a.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = a.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = a.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = a.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DECIMAL
        ) AS MonthsUntilRenewal
    FROM ehr_compliancedb.employeerequirementexemptions a
    WHERE a.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE a.employeeid = p.employeeid AND p.enddate IS NULL)
      AND a.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = a.requirementname AND q.dateDisabled IS NULL)
    GROUP BY a.requirementname, a.employeeid

    UNION

    SELECT
        j.requirementname,
        j.employeeid,
        NULL AS unit,
        NULL AS category,
        string_agg(j.trackingflag, chr(10)) AS trackingflag,
        (SELECT h.email FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS email,
        (SELECT h.lastname FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS lastname,
        (SELECT h.firstname FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS firstname,
        (SELECT h.majorudds FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS host,
        (SELECT h.supervisor FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS supervisor,
        (SELECT h.type FROM ehr_compliancedb.employees h WHERE h.employeeid = j.employeeid) AS trainee_type,
        (SELECT h.type FROM ehr_compliancedb.Requirements h WHERE h.requirementname = j.requirementname) AS requirement_type,
        0 AS timesCompleted,
        (SELECT k.expireperiod FROM ehr_compliancedb.Requirements k WHERE k.requirementname = j.requirementname) AS ExpiredPeriod,
        (
            SELECT ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
            FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
            WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
            GROUP BY tt.expireperiod, tt.reviewdate
            HAVING (COALESCE(tt.expireperiod, 0)) > ((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
               AND (tt.reviewdate IS NOT NULL)
        ) AS NewExpirePeriod,
        NULL AS MostRecentDate,
        '' AS comment,
        NULL AS snooze_date,
        CAST(
            CASE
                WHEN (SELECT max(st.date) FROM ehr_compliancedb.completiondates st WHERE st.requirementname = j.requirementname AND st.employeeid = j.employeeid) IS NULL THEN 0
                WHEN (SELECT COALESCE(tt.expireperiod, 0) FROM ehr_compliancedb.requirements tt WHERE tt.requirementname = j.requirementname GROUP BY tt.expireperiod) = 0 THEN NULL
                WHEN (
                    SELECT count(*)
                    FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                    WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
                    GROUP BY tt.expireperiod, tt.reviewdate
                    HAVING tt.reviewdate > max(pq.date)
                ) > 0 THEN
                    (
                        SELECT (((EXTRACT(YEAR FROM tt.reviewdate) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM tt.reviewdate) - EXTRACT(MONTH FROM max(pq.date)))
                                - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date))))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
                        GROUP BY tt.expireperiod, tt.reviewdate
                        HAVING tt.reviewdate > max(pq.date)
                    )
                ELSE
                    (
                        SELECT COALESCE(tt.expireperiod, 0) - ((EXTRACT(YEAR FROM now()) - EXTRACT(YEAR FROM max(pq.date))) * 12 + EXTRACT(MONTH FROM now()) - EXTRACT(MONTH FROM max(pq.date)))
                        FROM ehr_compliancedb.requirements tt, ehr_compliancedb.completiondates pq
                        WHERE tt.requirementname = j.requirementname AND pq.requirementname = tt.requirementname AND pq.employeeid = j.employeeid
                        GROUP BY tt.expireperiod
                    )
            END AS DOUBLE PRECISION
        ) AS MonthsUntilRenewal
    FROM onprc_ehr_compliancedb.RequirementsPerEmployee j
    WHERE j.employeeid IN (SELECT p.employeeid FROM ehr_compliancedb.employees p WHERE j.employeeid = p.employeeid AND p.enddate IS NULL)
      AND j.requirementname IN (SELECT q.requirementname FROM ehr_compliancedb.Requirements q WHERE q.requirementname = j.requirementname AND q.dateDisabled IS NULL)
      AND j.requirementname NOT IN (
          SELECT DISTINCT h.requirementname
          FROM ehr_compliancedb.employeeperunit k, ehr_compliancedb.requirementspercategory h
          WHERE (k.unit = h.unit OR k.category = h.category) AND j.employeeid = k.employeeid
      )
      AND j.requirementname NOT IN (SELECT DISTINCT t.requirementname FROM ehr_compliancedb.employeerequirementexemptions t WHERE j.employeeid = t.employeeid AND j.requirementname = t.requirementname)
      AND j.requirementname NOT IN (SELECT DISTINCT k.requirementname FROM ehr_compliancedb.completiondates k WHERE k.employeeid = j.employeeid)
    GROUP BY j.requirementname, j.employeeid
    ORDER BY employeeid, requirementname, mostrecentcompleted_date DESC;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 1;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION onprc_ehr_compliancedb.p_ComplianceAccesscontainerUpdate()
RETURNS integer AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM ehr_compliancedb.completiondates WHERE container = 'F1C05E2D-618D-103D-ABC9-9814909BFFCD') THEN
        UPDATE ehr_compliancedb.completiondates
        SET container = 'CD170458-C55F-102F-9907-5107380A54BE'
        WHERE container = 'F1C05E2D-618D-103D-ABC9-9814909BFFCD';
    END IF;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 1;
END;
$$ LANGUAGE plpgsql;
