SELECT i.invoiceId,
       i.transactionNumber,
       i.Id,
       i.item,
       i.itemCode,
       i.category,
       i.servicecenter,
       i.project,
       i.debitedaccount,
       i.creditedaccount,
       i.faid,
       i.investigatorId,
       i.lastName,
       i.firstName,
       i.quantity,
       i.unitCost,
       i.date,
       c.unitcost as NIHRate,
       i.totalcost,
       i.comment,
       i.chargecategory,
       i.isAssignedAtTime,
       i.isAssignedToProtocolAtTime,
       i.pendingAdjustments,
       i.totalAdjustments
FROM invoicedItems i,onprc_billing.chargeRates c
where i.itemcode = c.chargeid.itemcode and  (i.date> c.startDate and i.date < c.enddate)