#!/bin/sh
#
# Plugin to graph httpresponse time of a specific page
#
# Parameters:
#
#       target      - overrides the default 'index.html' page
#       PATH        - set a sensible path
#
#
#
# $Id: $
#
#%# family=auto
#%# capabilities=autoconf

time_bin=$(which time)
wget_bin=$(which wget)

if [ "$1" = "autoconf" ]; then
    result="yes"
    [ "x$time_bin" = "x" ] && result=1
    [ "x$wget_bin" = "x" ] && result=2
    if [ "$result" != "yes" ]; then
	echo "no (need time and wget programs)"
	exit 1
    fi
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo "graph_title HTTP loadtime of a page: $label"
    echo "graph_args --base 1000 -l 0"
    echo "graph_vlabel Load time in seconds"
    echo "graph_category page_loads"
    echo "graph_info This graph shows load time in seconds of $base_url"
    echo "loadtime.label $label"
    echo "loadtime.info Load time"
    exit 0
fi

#[ "$target"  ] && base_url=$target

#[ "$base_url" ] || exit 1

TMPFILE=$(mktemp)

#echo $TMPFILE
TMPDIR=$(dirname $TMPFILE)
DEBUG=/tmp/tmpfile

trap 'rm -rf $TMPFILE' EXIT
cd $TMPDIR || exit 1

post="email=${username}&password=${password}"
url="${base_url}login/login.post";

#echo 1 >$DEBUG
#echo $url >>$DEBUG
/usr/bin/wget --no-cache --no-check-certificate --delete-after --post-data "$post" --save-cookies cookies.munin --keep-session-cookies "$url" 2>>$DEBUG;

url="${base_url}${target}"

#/usr/bin/wget --no-cache --no-check-certificate --delete-after --load-cookie cookies.munin "$url" 2>>$DEBUG
/usr/bin/time -p /usr/bin/wget --no-cache --no-check-certificate --delete-after --load-cookie $TMPDIR/cookies.munin "$url" 3>&2 2>$TMPFILE

loadtime=$(awk '/^real / { print $2 }' $TMPFILE)

rm cookies.munin
cd .

echo $loadtime >> $DEBUG
echo "loadtime.value $loadtime"