SELECT
  'Order' as type,
  t.Id,
  t.date,
  t.enddate,
  t.project,
  null as chargetype,
  t.category,
  t.code,
  t.frequency,
  t.route,
  t.concentration,
  t.conc_units,
  t.dosage,
  t.dosage_units,
  t.volume,
  t.vol_units,
  t.amount,
  t.amount_units,
  t.performedby,
  t.remark,
  t.taskid,
  t.requestid,
  t.container,
  t.lsid,
  t.objectid,
  t.qcstate,
  t.created,
  t.createdby,
  t.modified,
  t.modifiedby

FROM study.treatment_order t

UNION ALL

SELECT
  'One Time' as type,
  d.Id,
  d.date,
  null as enddate,
  d.project,
  d.chargetype,
  d.category,
  d.code,
  null as frequency,
  d.route,
  d.concentration,
  d.conc_units,
  d.dosage,
  d.dosage_units,
  d.volume,
  d.vol_units,
  d.amount,
  d.amount_units,
  d.performedby,
  d.remark,
  d.taskid,
  d.requestid,
  d.container,
  d.lsid,
  d.objectid,
  d.qcstate,
  d.created,
  d.createdby,
  d.modified,
  d.modifiedby

FROM study.drug d
WHERE d.treatmentid IS NULL