SELECT p.rowid,
       p.Protocol_ID,
       p.Template_OID,
       p.Protocol_OID,
       p.Protocol_Title,
       p.PI_ID,
       p.PI_First_Name,
       p.PI_Last_Name,
       p.PI_Email,
       p.PI_Phone,
       p.USDA_Level,
       p.Approval_Date,
       p.Annual_Update_Due,
       p.Three_year_Expiration,
       p.Last_Modified,
       p.PROTOCOL_State,
       p.PPQ_Numbers,
       p.Description,
       p.baseProtocol,
       p.RenewalNumber,
       p.LatestRenewal,
       e.enddate
FROM eIACUC_PRIME_VIEW_PROTOCOLS p left outer join ehr.protocol e on p.BaseProtocol = e.external_ID
where p.Protocol_State like 'expired'