INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Abnormal', 'Value is abnormal', TRUE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Completed', 'Record has been completed and is public', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Delete Requested', 'Records are requested to be deleted', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('In Progress', 'Draft Record, not public', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Request: Approved', 'Request has been approved', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Request: Denied', 'Request has been denied', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Request: Pending', 'Part of a request that has not been approved', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Review Required', 'Review is required prior to public release', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
INSERT INTO study.qcstate (label,description,publicdata,container) VALUES ('Scheduled', 'Record is scheduled, but not performed', FALSE, (SELECT entityid FROM core.containers WHERE name='EHR' AND parent = (SELECT entityid FROM core.containers WHERE name='ONPRC')));
