-- =================================================================================================
-- Created by Kollil
-- These tables and stored proc was created to enter weaning data into SLA tables
-- Refer to ticket #11233
-- =================================================================================================

CREATE TABLE sla.weaning (
    rowid SERIAL,
    investigator varchar(250),
    date TIMESTAMP,             -- Pup's DOB
    project varchar(200),
    vendorLocation varchar(200),
    DOB TIMESTAMP,              -- Dam's DOB
    DOM TIMESTAMP,              -- Date of Mating
    species varchar(100),
    sex varchar(100),
    strain varchar(200),
    numAlive INTEGER,
    numDead INTEGER,
    totalPups INTEGER,
    dateofTransfer TIMESTAMP,   -- The date of transfer into SLA tables
    createdBy USERID,
    created TIMESTAMP,
    modifiedBy USERID,
    modified TIMESTAMP,

    CONSTRAINT PK_weaning PRIMARY KEY (rowid)
);

/*
** onprc_ehr.SLAWeaningDataTransfer
**
** Author: Lakshmi Kolli
** Create date: 8/24/2024
** Description: Check for any rodents with age >= 21 days and enter the data into SLA tables.
**
*/
CREATE OR REPLACE FUNCTION onprc_ehr.SLAWeaningDataTransfer()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_WCount            int;
    v_alias             varchar(100);
    v_purchaseId        ENTITYID;
    v_center_project    int;
    v_center_project2   int;
    v_counter           int;
    v_counter2          int;
    v_DOT               TIMESTAMP;
    v_DOT2              TIMESTAMP;
BEGIN
    -- Check if any rodents age is 21 days and above and not transferred into SLA tables
    SELECT COUNT(*) INTO v_WCount
    FROM sla.weaning
    WHERE numAlive > 0
      AND dateofTransfer IS NULL
      AND (now()::date - date::date) >= 21;

    -- Found entries, so insert those records into sla.purchase and sla.purchasedetails tables
    IF v_WCount > 0 THEN -- start if, 1

        -- Local temp table used to process the weaning data. ON COMMIT DROP replaces the #TempWeaning
        -- session scoping; the DROP IF EXISTS guards against two calls inside one transaction.
        DROP TABLE IF EXISTS TempWeaning;
        CREATE TEMP TABLE TempWeaning (
            rowid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
            orig_weaning_rowid INTEGER,
            investigator varchar(250),
            date TIMESTAMP,
            project varchar(200),
            vendorLocation varchar(200),
            DOB TIMESTAMP,
            DOM TIMESTAMP,
            species varchar(100),
            sex varchar(100),
            strain varchar(200),
            numAlive INTEGER,
            dateofTransfer TIMESTAMP,
            created TIMESTAMP
        ) ON COMMIT DROP;

        -- Move the weaning entries into the temp table
        INSERT INTO TempWeaning (orig_weaning_rowid, investigator, date, project, vendorlocation, DOB, DOM, species, sex, strain, numAlive, created)
        SELECT rowid, investigator, date, project, vendorlocation, date, DOM, species,
            CASE
                WHEN lower(sex) = lower('F') THEN 'Female'
                WHEN lower(sex) = lower('M') THEN 'Male'
                ELSE 'Male or Female'
            END AS sex,
            strain, numAlive, now()
        FROM sla.weaning
        WHERE numAlive > 0
          AND dateofTransfer IS NULL
          AND (now()::date - date::date) >= 21;

        -- Set the counter seed value
        SELECT rowid INTO v_counter FROM TempWeaning ORDER BY rowid ASC LIMIT 1;

        WHILE v_counter <= v_WCount LOOP -- start 1st while

            /* Requestorid - (Kati Marshall ) - 7B3F1ED1-4CD9-4D9A-AFF4-FE0618D49C4B
               Userid - (Kati Marshall) - 1294
               vendor - (ONPRC Weaning - SLA) - E1EE1B64-B7BE-1035-BFC4-5107380AE41E
               container - (SLA) - 4831D09C-4169-1034-BAD2-5107380A9819
               created - (onprc-is) - 1003
            */

            SELECT dateofTransfer INTO v_DOT FROM TempWeaning WHERE rowid = v_counter;

            IF v_DOT IS NULL THEN -- start v_DOT

                -- Get projectid, PI and account
                SELECT p.project, p.account INTO v_center_project, v_alias
                FROM ehr.project p
                WHERE lower(p.name) = lower((SELECT t.project FROM TempWeaning t WHERE t.rowid = v_counter));

                -- Generate the purchase objectid up front so the purchaseDetails rows below can
                -- reference it directly, rather than reading it back by created date.
                v_purchaseId := gen_random_uuid()::ENTITYID;

                -- Insert weaning data into sla.purchase table as a pending order
                INSERT INTO sla.purchase
                    (project, account, requestorid, vendorid, hazardslist, dobrequired, comments, confirmationnum, housingconfirmed,
                     iacucconfirmed, requestdate, orderdate, orderedby, objectid, container, createdby, created, modifiedby, modified, darcomments, vendorcontact)
                SELECT v_center_project, v_alias, '7B3F1ED1-4CD9-4D9A-AFF4-FE0618D49C4B', 'E1EE1B64-B7BE-1035-BFC4-5107380AE41E', '', 0, '', null, null, null, null, null, '', v_purchaseId,
                       '4831D09C-4169-1034-BAD2-5107380A9819', 1003, now(), null, null, '', '';

                -- Insert data into purchasedetails with the purchaseid created above
                INSERT INTO sla.purchaseDetails
                    (purchaseid, species, age, weight, weight_units, gestation, gender, strain, room, animalsordered, animalsreceived, boxesquantity, costperanimal, shippingcost,
                     totalcost, housingInstructions, requestedarrivaldate, expectedarrivaldate, receiveddate, receivedby, cancelledby, datecancelled,
                     objectid, container, createdby, created, modifiedby, modified, sla_DOB, vendorLocation)
                SELECT v_purchaseId, t.species, (now()::date - t.date::date)::varchar || ' days', '', '', '', t.sex, t.strain, '', t.numAlive, null, null, '', '',
                       '', '', t.date + INTERVAL '21 days', t.date + INTERVAL '21 days', null, '', '', null,
                       gen_random_uuid()::ENTITYID, '4831D09C-4169-1034-BAD2-5107380A9819', 1003, now(), null, null, t.date, t.vendorLocation
                FROM TempWeaning t WHERE t.rowid = v_counter;

                -- Update the sla.weaning row with the date of transfer for the transferred weaning row
                UPDATE sla.weaning
                SET dateofTransfer = now()
                WHERE rowid = (SELECT t.orig_weaning_rowid FROM TempWeaning t WHERE t.rowid = v_counter);

                UPDATE TempWeaning
                SET dateofTransfer = now()
                WHERE rowid = v_counter;

                -- Find if there are any rows with the same center project. Then create them under the same purchaseId.
                -- Set the new counter
                v_counter2 := v_counter + 1;

                WHILE v_counter2 <= v_WCount LOOP -- start 2nd while

                    SELECT dateofTransfer INTO v_DOT2 FROM TempWeaning WHERE rowid = v_counter2;

                    IF v_DOT2 IS NULL THEN

                        -- Get projectid of the next row
                        SELECT p.project INTO v_center_project2
                        FROM ehr.project p
                        WHERE lower(p.name) = lower((SELECT t.project FROM TempWeaning t WHERE t.rowid = v_counter2));

                        -- If they are the same project, then use the same purchaseid when creating the purchase details record
                        IF (v_center_project = v_center_project2) THEN -- start if, 2

                            INSERT INTO sla.purchaseDetails
                                (purchaseid, species, age, weight, weight_units, gestation, gender, strain, room, animalsordered, animalsreceived, boxesquantity, costperanimal, shippingcost,
                                 totalcost, housingInstructions, requestedarrivaldate, expectedarrivaldate, receiveddate, receivedby, cancelledby, datecancelled,
                                 objectid, container, createdby, created, modifiedby, modified, sla_DOB, vendorLocation)
                            SELECT v_purchaseId, t.species, (now()::date - t.date::date)::varchar || ' days', '', '', '', t.sex, t.strain, '', t.numAlive, null, null, '', '',
                                   '', '', t.date + INTERVAL '21 days', t.date + INTERVAL '21 days', null, '', '', null,
                                   gen_random_uuid()::ENTITYID, '4831D09C-4169-1034-BAD2-5107380A9819', 1003, now(), null, null, t.date, t.vendorLocation
                            FROM TempWeaning t WHERE t.rowid = v_counter2;

                            UPDATE sla.weaning
                            SET dateofTransfer = now()
                            WHERE rowid = (SELECT t.orig_weaning_rowid FROM TempWeaning t WHERE t.rowid = v_counter2);

                            UPDATE TempWeaning
                            SET dateofTransfer = now()
                            WHERE rowid = v_counter2;

                        END IF; -- end if, 2

                    END IF; -- end v_DOT2

                    v_counter2 := v_counter2 + 1;

                END LOOP; -- end, 2nd while

            END IF; -- end v_DOT

            v_counter := v_counter + 1;

        END LOOP; -- end, 1st while

    END IF; -- end if, 1

    RETURN 0;
END;
$$;
