ALTER TABLE onprc_ehr.eIACUC_PRIME_VIEW_PROTOCOLS DROP COLUMN IF EXISTS BaseProtocol;
ALTER TABLE onprc_ehr.eIACUC_PRIME_VIEW_PROTOCOLS DROP COLUMN IF EXISTS RevisionNumber;
ALTER TABLE onprc_ehr.eIACUC_PRIME_VIEW_PROTOCOLS DROP COLUMN IF EXISTS UpdateStatus;


ALTER TABLE [onprc_ehr].[eIACUC_PRIME_VIEW_PROTOCOLS] ADD  BaseProtocol varchar(50) ;
ALTER TABLE [onprc_ehr].[eIACUC_PRIME_VIEW_PROTOCOLS] ADD  RenewalNumber varchar(50) ;
ALTER TABLE [onprc_ehr].[eIACUC_PRIME_VIEW_PROTOCOLS] ADD  LatestRenewal Bit ;