ALTER TABLE onprc_billing.ogaSynch DROP COLUMN IF EXISTS OGA_AWARD_START_DATE CASCADE;
ALTER TABLE onprc_billing.ogaSynch DROP COLUMN IF EXISTS OGA_AWARD_END_DATE CASCADE;
ALTER TABLE onprc_billing.ogaSynch DROP COLUMN IF EXISTS IndirectRate CASCADE;

ALTER TABLE onprc_billing.ogaSynch ADD OGA_AWARD_START_DATE DATE NULL;
ALTER TABLE onprc_billing.ogaSynch ADD OGA_AWARD_END_DATE DATE NULL;
ALTER TABLE onprc_billing.ogaSynch ADD IndirectRate DOUBLE PRECISION NULL;
