-- Cleanly drop existing tables and functions using standard PostgreSQL DDL
DROP TABLE IF EXISTS onprc_ehr.TB_TestTemp;
DROP TABLE IF EXISTS onprc_ehr.TB_TestTempMaster;
DROP TABLE IF EXISTS onprc_ehr.Temp_Clinical_Observations;
DROP TABLE IF EXISTS onprc_ehr.Temp_Clinical_Observations_Master;
DROP TABLE IF EXISTS onprc_ehr.Observation_EHRTasks;
DROP FUNCTION IF EXISTS onprc_ehr.p_Create_TB_Observationrecords();

-- Create TB_TestTemp table
CREATE TABLE onprc_ehr.TB_TestTemp (
    rowid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    animalid varchar(200) NULL,
    date timestamp NULL,
    objectid ENTITYID NOT NULL, -- Maintained ENTITYID data type as requested
    created timestamp NULL,
    createdby integer NULL,
    performedby varchar(200) NULL,
    modifiedby integer NULL,
    date_posted timestamp(0) NULL,
    CONSTRAINT PK_TB_TestTemp PRIMARY KEY (rowid)
);

-- Create Temp_Clinical_Observations table
CREATE TABLE onprc_ehr.Temp_Clinical_Observations (
    rowid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    Id varchar(200) NULL,
    date timestamp(0) NULL,
    category varchar(500) NULL,
    area varchar(500) NULL,
    observation varchar(500) NULL,
    createdby integer NULL,
    performedby varchar(500) NULL,
    taskid varchar(4000) NULL,
    qcstate integer NULL,
    modifiedby integer NULL,
    CONSTRAINT PK_Temp_Clinical_Observations PRIMARY KEY (rowid)
);

-- Create Temp_Clinical_Observations_Master table
CREATE TABLE onprc_ehr.Temp_Clinical_Observations_Master (
    rowid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    searchid integer NULL,
    Id varchar(200) NULL,
    date timestamp(0) NULL,
    category varchar(500) NULL,
    area varchar(500) NULL,
    observation varchar(500) NULL,
    createdby integer NULL,
    performedby varchar(500) NULL,
    taskid varchar(4000) NULL,
    qcstate smallint NULL,
    modifiedby timestamp(0) NULL, -- Maintained smalldatetime equivalent
    Posted_date timestamp(0) NULL,
    CONSTRAINT PK_Temp_Clinical_Observations_Master PRIMARY KEY (rowid)
);

-- Create Observation_EHRTasks table
CREATE TABLE onprc_ehr.Observation_EHRTasks (
    rowid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    taskid varchar(4000) NULL,
    description varchar(500) NULL,
    title varchar(500) NULL,
    qcstate smallint NULL,
    formtype varchar(500) NULL,
    category varchar(500) NULL,
    assignedto smallint NULL,
    createdby smallint NULL,
    modifiedby smallint NULL,
    CONSTRAINT PK_Observation_EHRTasks PRIMARY KEY (rowid)
);

/*
**
** 	Created by
**      R. Blasa   6-24-2026      A  Program Process that reviews all TB Test Encounter entries on a current date, and creates a
**                                     new TB Test Clinical Observation record based on
**                                     having the same monkey id, date, and then to be assigned to a Data Admin for reviews.
**
**                             Modified program so that each Clinical Observation entries generated by the program is assigned
**                                only a single task id when the program executes daily.
**
**
*/

CREATE OR REPLACE FUNCTION onprc_ehr.p_Create_TB_Observationrecords()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_SearchKey          integer;
    v_TempSearchKey      integer;
    v_TaskId             varchar(4000);
    v_AnimalID           varchar(100);
    v_date               timestamp(0);
    v_createdby          integer;
    v_performedby        varchar(500);
    v_modifiedby         integer;
    v_RunID              varchar(4000);
    v_FirstFlag          integer;
    v_TestDate           timestamp(0);
BEGIN
    -- Reset temp tables
    TRUNCATE TABLE onprc_ehr.TB_TestTemp;
    TRUNCATE TABLE onprc_ehr.Temp_Clinical_Observations;
    TRUNCATE TABLE onprc_ehr.Observation_EHRTasks;

    -- Generate a list of TB test monkeys
    INSERT INTO onprc_ehr.TB_TestTemp (animalid, date, objectid, created, createdby, performedby, modifiedby, date_posted)
    SELECT
        a.participantid,
        a.date,
        a.objectid,
        a.created,
        a.createdBy,
        a.performedby,
        a.modifiedby,
        CURRENT_TIMESTAMP
    FROM studydataset.c6d214_encounters a
    WHERE a.type IN ('Procedure', 'Surgery')
      AND a.qcstate = 18
      AND a.procedureid = 802
      AND a.modified >= CURRENT_DATE
      AND a.participantid IN (
          SELECT k.participantid 
          FROM studydataset.c6d203_demographics k
          WHERE k.calculated_status = 'alive'
      )
      AND a.participantid NOT IN (
          SELECT j.participantid 
          FROM studydataset.c6d171_clinical_observations j
          WHERE j.participantid = a.participantid
            AND j.date = a.date + INTERVAL '3 days'
            AND j.category = 'TB TST Score (72 hr)'
            AND j.qcstate = 18
      );

    -- Exit early if no records were found to process (replacing GOTO No_Records)
    IF NOT EXISTS (SELECT 1 FROM onprc_ehr.TB_TestTemp) THEN
        RETURN 0;
    END IF;

    -- Reset temp variables
    v_SearchKey := 0;
    v_TempSearchKey := 0;
    v_date := NULL;
    v_modifiedby := NULL;
    v_createdby := NULL;
    v_performedby := NULL;
    v_TaskId := NULL;
    v_AnimalID := NULL;
    v_RunID := NULL;
    v_FirstFlag := 0;

    -- Extract initial rowid
    SELECT rowid INTO v_SearchKey 
    FROM onprc_ehr.TB_TestTemp
    ORDER BY rowid
    LIMIT 1;

    -- Loop to create tasks and clinical observations
    WHILE v_TempSearchKey < v_SearchKey LOOP
        
        SELECT animalid, date, modifiedby, createdby, performedby
        INTO v_AnimalID, v_date, v_modifiedby, v_createdby, v_performedby
        FROM onprc_ehr.TB_TestTemp 
        WHERE rowid = v_SearchKey;

        IF NOT EXISTS (
            SELECT 1 FROM studydataset.c6d171_clinical_observations j 
            WHERE j.participantid = v_AnimalID
              AND j.date = v_date + INTERVAL '3 days'
              AND j.category = 'TB TST Score (72 hr)'
              AND j.qcstate = 18
        ) THEN

            IF v_FirstFlag != 1 THEN
                -- Create a new unique task ID
                v_TaskId := UPPER(gen_random_uuid()::text);

                -- Create Clinical Observation Task Entry
                INSERT INTO onprc_ehr.Observation_EHRTasks (
                    taskid,
                    description,
                    title,
                    qcstate,
                    formtype,
                    category,
                    assignedto,
                    createdby,
                    modifiedby
                ) VALUES (
                    v_TaskId,
                    'TB TST Scores ' || COALESCE(v_date::text, ''),
                    'TB TST Scores',
                    20,
                    'TB TST Scores',
                    'task',
                    1822,
                    1042,
                    1042
                );

                v_FirstFlag := 1;
            END IF;

            -- Initialize data entries (Add three days from TB Test date)
            v_date := v_date + INTERVAL '3 days';

            -- Create a Clinical Observation Record
            INSERT INTO onprc_ehr.Temp_Clinical_Observations (
                Id,
                date,
                category,
                area,
                observation,
                createdby,
                performedby,
                taskid,
                qcstate,
                modifiedby
            ) VALUES (
                v_AnimalID,
                v_date,
                'TB TST Score (72 hr)',
                'Right Eyelid',
                'Grade: Negative',
                1042,
                v_performedby,
                v_TaskId,
                20,
                1042
            );

        END IF;

        -- Fetch the next record
        v_TempSearchKey := v_SearchKey;

        SELECT rowid INTO v_SearchKey 
        FROM onprc_ehr.TB_TestTemp
        WHERE rowid > v_TempSearchKey
        ORDER BY rowid
        LIMIT 1;

        IF NOT FOUND OR v_SearchKey IS NULL THEN
            EXIT;
        END IF;

    END LOOP;

    -- Create a master copy of the completed transaction with safe explicit column mapping.
    -- PostgreSQL handles the conversion of integer 'modifiedby' to timestamp(0) 'modifiedby' via epoch math.
    INSERT INTO onprc_ehr.Temp_Clinical_Observations_Master (
        searchid, Id, date, category, area, observation, createdby, performedby, taskid, qcstate, modifiedby, Posted_date
    )
    SELECT 
        rowid, 
        Id, 
        date, 
        category, 
        area, 
        observation, 
        createdby, 
        performedby, 
        taskid, 
        qcstate, 
        CASE 
            WHEN modifiedby IS NOT NULL THEN '1900-01-01'::timestamp + (modifiedby || ' days')::interval 
            ELSE NULL 
        END,
        CURRENT_TIMESTAMP
    FROM onprc_ehr.Temp_Clinical_Observations;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        -- Equivalent to the Err_Proc label rollback/failure return
        RETURN 1;
END;
$$;
