-- Current scripts create this as a FUNCTION, but earlier versions had created a PROCEDURE by this name. Tolerate that case.
DROP PROCEDURE IF EXISTS audit.ArchiveAuditTables;

CREATE OR REPLACE FUNCTION audit.ArchiveAuditTables(
    INOUT RetentionMonths INT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_DestSchema   TEXT := 'labkey_audit'; -- Destination schema representing the destination database/namespace
    v_SchemaName   TEXT := 'audit';
    v_CutoffDate   TIMESTAMP;
    v_LogID        INT;
    v_CurrentTable TEXT;
    v_ColumnList   TEXT;
    v_InsertCount  INT;
    v_ErrorMessage TEXT;
BEGIN
    RetentionMonths := CASE 
        WHEN RetentionMonths - 6 > 12 THEN RetentionMonths - 6 
        ELSE 12 
    END;

    RAISE NOTICE 'Archiving audit logs older than % months old', RetentionMonths;

    v_CutoffDate := CURRENT_TIMESTAMP - (RetentionMonths || ' months')::INTERVAL;

    -- Validate source schema exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = v_SchemaName) THEN
        RAISE EXCEPTION 'Source schema "%" does not exist', v_SchemaName;
    END IF;

    -- Create destination schema if not exists
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', v_DestSchema);

    -- Create ArchiveAuditLog table if not exists in destination schema
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.ArchiveAuditLog (
            LogID INT GENERATED BY DEFAULT AS IDENTITY,
            TableName VARCHAR(128) NOT NULL,
            Operation VARCHAR(50) NOT NULL,
            StartTime TIMESTAMP NOT NULL,
            EndTime TIMESTAMP NULL,
            Status VARCHAR(50) NULL,
            RecordsProcessed INT NULL,
            ErrorMessage TEXT NULL,
            RetentionMonths INT NULL,

            CONSTRAINT PK_ArchiveAuditLog PRIMARY KEY (LogID)
        )', v_DestSchema);

    -- Iterate over tables in source schema (excluding specified audit domains)
    FOR v_CurrentTable IN
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = v_SchemaName
          AND table_type = 'BASE TABLE'
          AND table_name NOT IN ('c3d330_userauditdomain', 'c3d317_groupauditdomain')
    LOOP
        -- Log the start of archiving for current table
        EXECUTE format('
            INSERT INTO %I.ArchiveAuditLog (TableName, Operation, StartTime, Status, RetentionMonths)
            VALUES ($1, ''Archive'', clock_timestamp(), ''Started'', $2)
            RETURNING LogID', v_DestSchema)
        INTO v_LogID
        USING v_CurrentTable, RetentionMonths;

        BEGIN
            -- Create destination table if it does not exist (cloning structure from source table)
            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS %I.%I (LIKE %I.%I INCLUDING ALL)',
                v_DestSchema, v_CurrentTable, v_SchemaName, v_CurrentTable
            );

            -- Build column list excluding identity columns and generated columns
            SELECT string_agg(quote_ident(column_name), ', ')
            INTO v_ColumnList
            FROM information_schema.columns
            WHERE table_schema = v_SchemaName
              AND table_name = v_CurrentTable
              AND is_identity = 'NO'
              AND is_generated = 'NEVER';

            -- Archive data: Insert records into destination and delete from source
            EXECUTE format('
                WITH moved_rows AS (
                    DELETE FROM %I.%I
                    WHERE Created < $1
                    RETURNING %s
                )
                INSERT INTO %I.%I (%s)
                SELECT %s FROM moved_rows',
                v_SchemaName, v_CurrentTable,
                v_ColumnList,
                v_DestSchema, v_CurrentTable, v_ColumnList,
                v_ColumnList
            )
            USING v_CutoffDate;

            GET DIAGNOSTICS v_InsertCount = ROW_COUNT;

            -- Update log with success status
            EXECUTE format('
                UPDATE %I.ArchiveAuditLog
                SET RecordsProcessed = $1,
                    EndTime = clock_timestamp(),
                    Status = ''Success''
                WHERE LogID = $2', v_DestSchema)
            USING v_InsertCount, v_LogID;

        EXCEPTION WHEN OTHERS THEN
            v_ErrorMessage := 'Error archiving ' || v_CurrentTable || ': ' || SQLERRM;

            EXECUTE format('
                UPDATE %I.ArchiveAuditLog
                SET EndTime = clock_timestamp(),
                    Status = ''Error'',
                    ErrorMessage = $1
                WHERE LogID = $2', v_DestSchema)
            USING v_ErrorMessage, v_LogID;

            RAISE WARNING '%', v_ErrorMessage;
        END;
    END LOOP;
END;
$$;
