CREATE TABLE onprc_ehr.Rpt_TempProblemList (
    searchid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    animalid varchar(200) NULL,
    date     timestamp NULL,
    objectid varchar(4000) NULL,
    caseid   varchar(4000) NULL
);

CREATE TABLE onprc_ehr.Rpt_TempProblemListMaster (
    searchid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    animalid varchar(200) NULL,
    date     timestamp NULL,
    objectid varchar(4000) NULL,
    caseid   varchar(4000) NULL
);

/*
**
**	 Created by	Date		Comment
**
** 	   blasa     7-7-2026   Process to update historical problem list records
**
**
**
*/

CREATE OR REPLACE FUNCTION onprc_ehr.s_MasterProblemHistoricalProcess()
RETURNS integer AS $$
DECLARE
    rec RECORD;
BEGIN
    ----- Reset the temp table
    DELETE FROM onprc_ehr.Rpt_TempProblemList;

    --- Set initial processing
    INSERT INTO onprc_ehr.Rpt_TempProblemList (animalid, date, objectid, caseid)
    SELECT  participantid,
            date,
            objectid,
            caseid
    FROM studydataset.c6d200_problem
    WHERE category = 'Wound'
      AND subcategory = 'Digit Amputation'
      AND qcstate = 18
    ORDER BY participantid;

    ------- Begin updating records
    FOR rec IN
        SELECT animalid, date, objectid
        FROM onprc_ehr.Rpt_TempProblemList
        ORDER BY searchid
    LOOP
        UPDATE studydataset.c6d200_problem pb
        SET subcategory = 'Digit Removal/Caudectomy'
        WHERE pb.Participantid = rec.animalid
          AND pb.objectid = rec.objectid;
    END LOOP;

    ---- Create an audit record of these entries
    INSERT INTO onprc_ehr.Rpt_TempProblemListMaster (animalid, date, objectid, caseid)
    SELECT animalid, date, objectid, caseid
    FROM onprc_ehr.Rpt_TempProblemList;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 1;
END;
$$ LANGUAGE plpgsql;
