-- Create temporary report processing table
CREATE TABLE IF NOT EXISTS onprc_ehr.Rpt_TempJmacDate(
    searchid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    animalid varchar(200) NULL,
    JBGRemovalDate timestamp(0) NULL,
    JBGActualRemovalDate timestamp(0) NULL,
    CONSTRAINT PK_Rpt_TempJmacDate PRIMARY KEY (searchid)
);

-- Create permanent removal date table
CREATE TABLE IF NOT EXISTS onprc_ehr.JmacRemovalDate(
    searchid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    Id varchar(100) NULL,
    JBGRemovalDate timestamp(0) NULL,
    JBGActualRemovalDate timestamp(0) NULL,
    DaysDiff double precision NULL,
    reason varchar(100) NULL,
    CONSTRAINT PK_JmacRemovalDate PRIMARY KEY (searchid)
);

/*
**
**	 Created by	Date		Comment
**
** 	   blasa     4/10/2026    Process to update jmac Removal date
**
**
**
**/

CREATE OR REPLACE FUNCTION onprc_ehr.s_JmacRemovalDateProcess()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_TempSearchKey      integer := 0;
    v_SearchKey          integer := 0;
    v_AnimalID           varchar(100);
    v_OrgRemovalDate     timestamp(0);
    v_ActualRemovalDate  timestamp(0);
BEGIN
    -- Reset the temp table
    DELETE FROM onprc_ehr.Rpt_TempJmacDate;

    -- Set initial processing
    -- Column list is explicitly defined to prevent conflicts with the auto-generated identity key
    INSERT INTO onprc_ehr.Rpt_TempJmacDate (animalid, JBGRemovalDate, JBGActualRemovalDate)
    SELECT Id, JBGRemovalDate, JBGActualRemovalDate
    FROM onprc_ehr.JmacRemovalDate
    ORDER BY searchid;

    -- Get first searchid
    SELECT searchid INTO v_SearchKey 
    FROM onprc_ehr.Rpt_TempJmacDate
    ORDER BY searchid
    LIMIT 1;

    -- If no records exist, exit early with success
    IF v_SearchKey IS NULL THEN
        RETURN 0;
    END IF;

    WHILE v_TempSearchKey < v_SearchKey LOOP
        v_AnimalID := '';
        v_OrgRemovalDate := NULL;
        v_ActualRemovalDate := NULL;

        -- Fetch current record
        SELECT animalid, JBGRemovalDate, JBGActualRemovalDate
        INTO v_AnimalID, v_OrgRemovalDate, v_ActualRemovalDate
        FROM onprc_ehr.Rpt_TempJmacDate 
        WHERE searchid = v_SearchKey;

        -- Begin updating target records
        UPDATE studydataset.c6d346_animal_group_members
        SET enddate = v_ActualRemovalDate
        WHERE Participantid = v_AnimalID
          AND enddate::date = v_OrgRemovalDate::date;

        -- Advance loop cursor
        v_TempSearchKey := v_SearchKey;

        SELECT searchid INTO v_SearchKey 
        FROM onprc_ehr.Rpt_TempJmacDate
        WHERE searchid > v_TempSearchKey
        ORDER BY searchid
        LIMIT 1;

        -- If no more records are found, exit the loop
        IF NOT FOUND OR v_SearchKey IS NULL THEN
            EXIT;
        END IF;

    END LOOP;

    RETURN 0;

EXCEPTION
    WHEN OTHERS THEN
        -- Equivalent to Err_Proc rollback/failure return
        RETURN 1;
END;
$$;
