CREATE PROCEDURE audit.ArchiveAuditTables(
    INOUT p_RetentionMonths INT
)
LANGUAGE plpgsql
AS $$
DECLARE
    -- Configuration variables
    v_SourceSchema VARCHAR(128) := 'audit';
    v_DestLogSchema VARCHAR(128) := 'labkey_audit';
    v_DestTableSchema VARCHAR(128) := 'labkey_audit_audit';
    
    -- Operational variables
    v_CutoffDate TIMESTAMP;
    v_CurrentTable RECORD;
    v_CreatedCol VARCHAR(128);
    v_LogID INT;
    v_ColumnList TEXT;
    v_SQL TEXT;
    v_RecordsInserted INT;
    v_RecordsDeleted INT;
    v_ErrorMessage TEXT;
BEGIN
    -- Calculate Retention Months
    p_RetentionMonths := CASE WHEN p_RetentionMonths - 6 > 12 THEN p_RetentionMonths - 6 ELSE 12 END;
    RAISE NOTICE 'Archiving audit logs older than % months old', p_RetentionMonths;
    
    v_CutoffDate := CURRENT_TIMESTAMP - (p_RetentionMonths || ' months')::INTERVAL;

    -- Validate if source schema exists
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = v_SourceSchema) THEN
        RAISE EXCEPTION 'Source schema "%" does not exist.', v_SourceSchema;
    END IF;

    -- Ensure destination schemas exist
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', v_DestLogSchema);
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', v_DestTableSchema);

    -- Create ArchiveAuditLog table if not exists
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I.ArchiveAuditLog (
            LogID INT GENERATED BY DEFAULT AS IDENTITY,
            TableName VARCHAR(128) NOT NULL,
            Operation VARCHAR(50) NOT NULL,
            StartTime TIMESTAMP NOT NULL,
            EndTime TIMESTAMP NULL,
            Status VARCHAR(50) NULL,
            RecordsProcessed INT NULL,
            ErrorMessage TEXT NULL,
            RetentionMonths INT NULL,
            CONSTRAINT PK_ArchiveAuditLog PRIMARY KEY (LogID)
        )', v_DestLogSchema);

    -- Create RetentionMonths column in ArchiveAuditLog table if it does not exist
    EXECUTE format('
        ALTER TABLE %I.ArchiveAuditLog 
        ADD COLUMN IF NOT EXISTS RetentionMonths INT NULL', v_DestLogSchema);

    -- Loop through all base tables in the source schema
    FOR v_CurrentTable IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = v_SourceSchema 
          AND table_type = 'BASE TABLE'
    LOOP
        -- Find the exact name of the 'Created' column (case-insensitive check)
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_schema = v_SourceSchema 
          AND table_name = v_CurrentTable.table_name 
          AND lower(column_name) = 'created'
        LIMIT 1
        INTO v_CreatedCol;

        -- If 'Created' column is not found, skip this table
        IF v_CreatedCol IS NULL THEN
            RAISE WARNING 'Table %.% does not have a "Created" column. Skipping.', v_SourceSchema, v_CurrentTable.table_name;
            CONTINUE;
        END IF;

        -- Insert log record and get LogID
        v_SQL := format('
            INSERT INTO %I.ArchiveAuditLog (TableName, Operation, StartTime, Status, RetentionMonths)
            VALUES ($1, ''Archive'', CURRENT_TIMESTAMP, ''Started'', $2)
            RETURNING LogID', v_DestLogSchema);
        EXECUTE v_SQL USING v_CurrentTable.table_name, p_RetentionMonths INTO v_LogID;

        -- Subtransaction block to handle errors per table
        BEGIN
            -- Create destination table if it does not exist
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = v_DestTableSchema 
                  AND table_name = v_CurrentTable.table_name
            ) THEN
                v_SQL := format('CREATE TABLE %I.%I AS SELECT * FROM %I.%I WHERE 1 = 0', 
                                v_DestTableSchema, v_CurrentTable.table_name, 
                                v_SourceSchema, v_CurrentTable.table_name);
                EXECUTE v_SQL;
            END IF;

            -- Get column list excluding identity and serial columns
            SELECT string_agg(quote_ident(a.attname), ', ')
            FROM pg_attribute a
            JOIN pg_class t ON a.attrelid = t.oid
            JOIN pg_namespace s ON t.relnamespace = s.oid
            LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
            WHERE s.nspname = v_SourceSchema
              AND t.relname = v_CurrentTable.table_name
              AND a.attnum > 0
              AND NOT a.attisdropped
              AND a.attidentity = ''
              AND (d.adbin IS NULL OR pg_get_expr(d.adbin, d.adrelid) NOT LIKE 'nextval%')
            INTO v_ColumnList;

            IF v_ColumnList IS NULL OR v_ColumnList = '' THEN
                RAISE EXCEPTION 'No valid columns found to archive for table %', v_CurrentTable.table_name;
            END IF;

            -- Archive rows to destination table
            v_SQL := format('INSERT INTO %I.%I (%s) SELECT %s FROM %I.%I WHERE %I < $1',
                            v_DestTableSchema, v_CurrentTable.table_name, v_ColumnList, v_ColumnList,
                            v_SourceSchema, v_CurrentTable.table_name, v_CreatedCol);
            EXECUTE v_SQL USING v_CutoffDate;
            GET DIAGNOSTICS v_RecordsInserted = ROW_COUNT;

            -- Delete archived rows from source table
            v_SQL := format('DELETE FROM %I.%I WHERE %I < $1',
                            v_SourceSchema, v_CurrentTable.table_name, v_CreatedCol);
            EXECUTE v_SQL USING v_CutoffDate;
            GET DIAGNOSTICS v_RecordsDeleted = ROW_COUNT;

            -- Update log record on success
            v_SQL := format('
                UPDATE %I.ArchiveAuditLog
                SET RecordsProcessed = $1,
                    EndTime = CURRENT_TIMESTAMP,
                    Status = ''Success''
                WHERE LogID = $2', v_DestLogSchema);
            EXECUTE v_SQL USING v_RecordsInserted, v_LogID;

        EXCEPTION WHEN OTHERS THEN
            -- Rollback of the subtransaction happens automatically here.
            -- Get the error message
            GET STACKED DIAGNOSTICS v_ErrorMessage = MESSAGE_TEXT;

            -- Update log record on failure
            v_SQL := format('
                UPDATE %I.ArchiveAuditLog
                SET EndTime = CURRENT_TIMESTAMP,
                    Status = ''Error'',
                    ErrorMessage = $1
                WHERE LogID = $2', v_DestLogSchema);
            EXECUTE v_SQL USING v_ErrorMessage, v_LogID;

            RAISE WARNING 'Error archiving table %: %', v_CurrentTable.table_name, v_ErrorMessage;
        END;
    END LOOP;
END;
$$;
