-- Create the conversion mapping table
CREATE TABLE onprc_ehr.RequirementName_Convert (
    searchid integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    PreviousDesignation varchar(255) NULL,
    afterName varchar(255) NULL,
    FileName varchar(1000) NULL,
    CONSTRAINT PK_RequirementName_Convert PRIMARY KEY (searchid) -- TODO: Note - no PK on SQL Server
);

/*
**
**	 Created by	Date		Comment
**
**
**  	Blasa      1/6/2026     Convert Compliance Requirement Names to its new predefined names.
*/

CREATE OR REPLACE FUNCTION onprc_ehr.sp_Compliance_requirementname_Update_Process()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_SearchKey      integer := 0;
    v_TempSearchKey  integer := 0;
    v_Code           varchar(500);
BEGIN
    -- Initial query to get the first searchid
    SELECT searchid INTO v_SearchKey  
    FROM onprc_ehr.RequirementName_Convert
    ORDER BY searchid
    LIMIT 1;

    -- If no records exist, exit early with success
    IF v_SearchKey IS NULL THEN
        RETURN 0;
    END IF;

    WHILE v_TempSearchKey < v_SearchKey LOOP
        
        -- Get the PreviousDesignation code for the current searchid
        SELECT PreviousDesignation INTO v_Code  
        FROM onprc_ehr.RequirementName_Convert
        WHERE searchid = v_SearchKey
        LIMIT 1;

        -- 1. Process Requirement Names
        UPDATE ehr_compliancedb.Requirements ss
        SET RequirementName = TRIM(jj.aftername) || ' ' || TRIM(jj.filename)
        FROM onprc_ehr.RequirementName_Convert jj 
        WHERE ss.RequirementName ILIKE TRIM(v_Code) || '%'
          AND jj.PreviousDesignation ILIKE TRIM(v_Code) || '%';

        -- 2. Process Completion Dates
        UPDATE ehr_compliancedb.CompletionDates ss
        SET RequirementName = TRIM(jj.aftername) || ' ' || TRIM(jj.filename)
        FROM onprc_ehr.RequirementName_Convert jj 
        WHERE ss.RequirementName ILIKE TRIM(v_Code) || '%'
          AND jj.PreviousDesignation ILIKE TRIM(v_Code) || '%';

        -- 3. Process Requirements per Employees
        UPDATE ehr_compliancedb.RequirementsPerEmployee ss
        SET RequirementName = TRIM(jj.aftername) || ' ' || TRIM(jj.filename)
        FROM onprc_ehr.RequirementName_Convert jj 
        WHERE ss.RequirementName ILIKE TRIM(v_Code) || '%'
          AND jj.PreviousDesignation ILIKE TRIM(v_Code) || '%';

        -- 4. Process Requirements per Categories
        UPDATE ehr_compliancedb.RequirementsPerCategory ss
        SET RequirementName = TRIM(jj.aftername) || ' ' || TRIM(jj.filename)
        FROM onprc_ehr.RequirementName_Convert jj 
        WHERE ss.RequirementName ILIKE TRIM(v_Code) || '%'
          AND jj.PreviousDesignation ILIKE TRIM(v_Code) || '%';

        -- 5. Process Employee Requirements Exemptions
        UPDATE ehr_compliancedb.EmployeeRequirementExemptions ss
        SET RequirementName = TRIM(jj.aftername) || ' ' || TRIM(jj.filename)
        FROM onprc_ehr.RequirementName_Convert jj 
        WHERE ss.RequirementName ILIKE TRIM(v_Code) || '%'
          AND jj.PreviousDesignation ILIKE TRIM(v_Code) || '%';

        -- Set temp key to current key to advance the cursor state
        v_TempSearchKey := v_SearchKey;

        -- Fetch the next searchid
        SELECT searchid INTO v_SearchKey  
        FROM onprc_ehr.RequirementName_Convert
        WHERE searchid > v_TempSearchKey
        ORDER BY searchid
        LIMIT 1;

        -- If no more records are found, exit the loop
        IF NOT FOUND OR v_SearchKey IS NULL THEN
            EXIT;
        END IF;

    END LOOP;

    RETURN 0;
END;
$$;
